[project]
name = "word2vec-demo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "gensim>=4.3.3",
    "ipykernel>=6.29.5",
    "numpy>=1.26.4",
    "pandas>=2.3.1",
    "scikit-learn>=1.7.1",
]
